DROP DATABASE IF EXISTS quiz_emporium_db;

CREATE DATABASE quiz_emporium_db;


DROP TABLE IF EXISTS answers;

CREATE TABLE answers (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  answer VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS correct_answers;

CREATE TABLE correct_answers (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  
  FOREIGN KEY (quiz_id)
  REFERENCES quiz(id)
  ON DELETE SET NULL,
   
  FOREIGN KEY (answer_id)
  REFERENCES answer(id)
  ON DELETE SET NULL
);

DROP TABLE IF EXISTS questions;

CREATE TABLE questions (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  question VARCHAR(255) NOT NULL,
  FOREIGN KEY (quiz_id)
  REFERENCES quiz(id)
  ON DELETE SET NULL
);




DROP TABLE IF EXISTS user;

CREATE TABLE user (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  pw VARCHAR(255) NOT NULL,

);

DROP TABLE IF EXISTS quiz;

CREATE TABLE quiz (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
    FOREIGN KEY (user_id)
  REFERENCES user(id)
  ON DELETE SET NULL,
  created_at DATETIME NOT NULL

);